// Code generated by internal/modelgen. DO NOT EDIT.

package model

import "time"

// TableNames contains every table represented by this model release.
var TableNames = []string{
	"artist",
	"artist_alias",
	"artist_group",
	"artist_member",
	"artist_name_variation",
	"artist_url",
	"discogs_dump",
	"discogs_import_checkpoint",
	"discogs_import_run",
	"discogs_import_run_chunk",
	"discogs_import_run_dump",
	"genre",
	"label",
	"label_release_item",
	"label_sub_label",
	"label_url",
	"master",
	"master_artist",
	"master_genre",
	"master_style",
	"master_video",
	"release_item",
	"release_item_artist",
	"release_item_credited_artist",
	"release_item_format",
	"release_item_genre",
	"release_item_identifier",
	"release_item_image",
	"release_item_style",
	"release_item_track",
	"release_item_video",
	"release_item_work",
	"style",
}

// Artist represents a row in artist.
type Artist struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	DataQuality    *string   `db:"data_quality" json:"data_quality" gorm:"column:data_quality"`
	Name           *string   `db:"name" json:"name" gorm:"column:name"`
	Profile        *string   `db:"profile" json:"profile" gorm:"column:profile"`
	RealName       *string   `db:"real_name" json:"real_name" gorm:"column:real_name"`
}

// TableName returns the PostgreSQL table represented by Artist.
func (Artist) TableName() string { return "artist" }

// ArtistAlias represents a row in artist_alias.
type ArtistAlias struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	AliasID        int32     `db:"alias_id" json:"alias_id" gorm:"column:alias_id"`
	ArtistID       int32     `db:"artist_id" json:"artist_id" gorm:"column:artist_id"`
}

// TableName returns the PostgreSQL table represented by ArtistAlias.
func (ArtistAlias) TableName() string { return "artist_alias" }

// ArtistGroup represents a row in artist_group.
type ArtistGroup struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	ArtistID       int32     `db:"artist_id" json:"artist_id" gorm:"column:artist_id"`
	GroupID        int32     `db:"group_id" json:"group_id" gorm:"column:group_id"`
}

// TableName returns the PostgreSQL table represented by ArtistGroup.
func (ArtistGroup) TableName() string { return "artist_group" }

// ArtistMember represents a row in artist_member.
type ArtistMember struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	ArtistID       int32     `db:"artist_id" json:"artist_id" gorm:"column:artist_id"`
	MemberID       int32     `db:"member_id" json:"member_id" gorm:"column:member_id"`
}

// TableName returns the PostgreSQL table represented by ArtistMember.
func (ArtistMember) TableName() string { return "artist_member" }

// ArtistNameVariation represents a row in artist_name_variation.
type ArtistNameVariation struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	Hash           int32     `db:"hash" json:"hash" gorm:"column:hash"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	NameVariation  string    `db:"name_variation" json:"name_variation" gorm:"column:name_variation"`
	ArtistID       int32     `db:"artist_id" json:"artist_id" gorm:"column:artist_id"`
}

// TableName returns the PostgreSQL table represented by ArtistNameVariation.
func (ArtistNameVariation) TableName() string { return "artist_name_variation" }

// ArtistURL represents a row in artist_url.
type ArtistURL struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	Hash           int32     `db:"hash" json:"hash" gorm:"column:hash"`
	URL            string    `db:"url" json:"url" gorm:"column:url"`
	ArtistID       int32     `db:"artist_id" json:"artist_id" gorm:"column:artist_id"`
}

// TableName returns the PostgreSQL table represented by ArtistURL.
func (ArtistURL) TableName() string { return "artist_url" }

// DiscogsDump represents a row in discogs_dump.
type DiscogsDump struct {
	ID             int64     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	ETag           string    `db:"etag" json:"etag" gorm:"column:etag"`
	DumpDate       time.Time `db:"dump_date" json:"dump_date" gorm:"column:dump_date"`
	EntityType     string    `db:"entity_type" json:"entity_type" gorm:"column:entity_type"`
	ChecksumSHA256 string    `db:"checksum_sha256" json:"checksum_sha256" gorm:"column:checksum_sha256"`
	SizeBytes      int64     `db:"size_bytes" json:"size_bytes" gorm:"column:size_bytes"`
	URI            string    `db:"uri" json:"uri" gorm:"column:uri"`
}

// TableName returns the PostgreSQL table represented by DiscogsDump.
func (DiscogsDump) TableName() string { return "discogs_dump" }

// DiscogsImportCheckpoint represents a row in discogs_import_checkpoint.
type DiscogsImportCheckpoint struct {
	EntityType       *string    `db:"entity_type" json:"entity_type" gorm:"column:entity_type"`
	DumpDate         *time.Time `db:"dump_date" json:"dump_date" gorm:"column:dump_date"`
	ChecksumSHA256   *string    `db:"checksum_sha256" json:"checksum_sha256" gorm:"column:checksum_sha256"`
	SizeBytes        *int64     `db:"size_bytes" json:"size_bytes" gorm:"column:size_bytes"`
	ETag             *string    `db:"etag" json:"etag" gorm:"column:etag"`
	URI              *string    `db:"uri" json:"uri" gorm:"column:uri"`
	ImportRunID      *int64     `db:"import_run_id" json:"import_run_id" gorm:"column:import_run_id"`
	Processor        *string    `db:"processor" json:"processor" gorm:"column:processor"`
	ProcessorVersion *string    `db:"processor_version" json:"processor_version" gorm:"column:processor_version"`
	AppliedAt        *time.Time `db:"applied_at" json:"applied_at" gorm:"column:applied_at"`
	ResumedFromRunID *int64     `db:"resumed_from_run_id" json:"resumed_from_run_id" gorm:"column:resumed_from_run_id"`
}

// TableName returns the PostgreSQL table represented by DiscogsImportCheckpoint.
func (DiscogsImportCheckpoint) TableName() string { return "discogs_import_checkpoint" }

// DiscogsImportRun represents a row in discogs_import_run.
type DiscogsImportRun struct {
	ID                      int64      `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt               time.Time  `db:"created_at" json:"created_at" gorm:"column:created_at"`
	StartedAt               time.Time  `db:"started_at" json:"started_at" gorm:"column:started_at"`
	CompletedAt             *time.Time `db:"completed_at" json:"completed_at" gorm:"column:completed_at"`
	ManifestSHA256          string     `db:"manifest_sha256" json:"manifest_sha256" gorm:"column:manifest_sha256"`
	Status                  string     `db:"status" json:"status" gorm:"column:status"`
	ForceRequested          bool       `db:"force_requested" json:"force_requested" gorm:"column:force_requested"`
	AllowDowngradeRequested bool       `db:"allow_downgrade_requested" json:"allow_downgrade_requested" gorm:"column:allow_downgrade_requested"`
	Processor               string     `db:"processor" json:"processor" gorm:"column:processor"`
	ProcessorVersion        string     `db:"processor_version" json:"processor_version" gorm:"column:processor_version"`
	FailureMessage          *string    `db:"failure_message" json:"failure_message" gorm:"column:failure_message"`
	ResumedFromRunID        *int64     `db:"resumed_from_run_id" json:"resumed_from_run_id" gorm:"column:resumed_from_run_id"`
}

// TableName returns the PostgreSQL table represented by DiscogsImportRun.
func (DiscogsImportRun) TableName() string { return "discogs_import_run" }

// DiscogsImportRunChunk represents a row in discogs_import_run_chunk.
type DiscogsImportRunChunk struct {
	ImportRunID    int64     `db:"import_run_id" json:"import_run_id" gorm:"column:import_run_id;primaryKey"`
	EntityType     string    `db:"entity_type" json:"entity_type" gorm:"column:entity_type;primaryKey"`
	ChunkIndex     int64     `db:"chunk_index" json:"chunk_index" gorm:"column:chunk_index;primaryKey"`
	FirstItemIndex int64     `db:"first_item_index" json:"first_item_index" gorm:"column:first_item_index"`
	ItemCount      int64     `db:"item_count" json:"item_count" gorm:"column:item_count"`
	CompletedAt    time.Time `db:"completed_at" json:"completed_at" gorm:"column:completed_at"`
}

// TableName returns the PostgreSQL table represented by DiscogsImportRunChunk.
func (DiscogsImportRunChunk) TableName() string { return "discogs_import_run_chunk" }

// DiscogsImportRunDump represents a row in discogs_import_run_dump.
type DiscogsImportRunDump struct {
	ImportRunID            int64      `db:"import_run_id" json:"import_run_id" gorm:"column:import_run_id;primaryKey"`
	EntityType             string     `db:"entity_type" json:"entity_type" gorm:"column:entity_type;primaryKey"`
	DumpID                 int64      `db:"dump_id" json:"dump_id" gorm:"column:dump_id"`
	ProcessedItems         int64      `db:"processed_items" json:"processed_items" gorm:"column:processed_items"`
	LastProgressAt         *time.Time `db:"last_progress_at" json:"last_progress_at" gorm:"column:last_progress_at"`
	CompletedAt            *time.Time `db:"completed_at" json:"completed_at" gorm:"column:completed_at"`
	ChunkSize              *int64     `db:"chunk_size" json:"chunk_size" gorm:"column:chunk_size"`
	TotalItems             *int64     `db:"total_items" json:"total_items" gorm:"column:total_items"`
	TotalChunks            *int64     `db:"total_chunks" json:"total_chunks" gorm:"column:total_chunks"`
	ImportContractRevision int32      `db:"import_contract_revision" json:"import_contract_revision" gorm:"column:import_contract_revision"`
}

// TableName returns the PostgreSQL table represented by DiscogsImportRunDump.
func (DiscogsImportRunDump) TableName() string { return "discogs_import_run_dump" }

// Genre represents a row in genre.
type Genre struct {
	Name string `db:"name" json:"name" gorm:"column:name;primaryKey"`
}

// TableName returns the PostgreSQL table represented by Genre.
func (Genre) TableName() string { return "genre" }

// Label represents a row in label.
type Label struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	ContactInfo    *string   `db:"contact_info" json:"contact_info" gorm:"column:contact_info"`
	DataQuality    *string   `db:"data_quality" json:"data_quality" gorm:"column:data_quality"`
	Name           *string   `db:"name" json:"name" gorm:"column:name"`
	Profile        *string   `db:"profile" json:"profile" gorm:"column:profile"`
}

// TableName returns the PostgreSQL table represented by Label.
func (Label) TableName() string { return "label" }

// LabelReleaseItem represents a row in label_release_item.
type LabelReleaseItem struct {
	ID               int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt        time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt   time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	CategoryNotation *string   `db:"category_notation" json:"category_notation" gorm:"column:category_notation"`
	LabelID          int32     `db:"label_id" json:"label_id" gorm:"column:label_id"`
	ReleaseItemID    int32     `db:"release_item_id" json:"release_item_id" gorm:"column:release_item_id"`
}

// TableName returns the PostgreSQL table represented by LabelReleaseItem.
func (LabelReleaseItem) TableName() string { return "label_release_item" }

// LabelSubLabel represents a row in label_sub_label.
type LabelSubLabel struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	ParentLabelID  int32     `db:"parent_label_id" json:"parent_label_id" gorm:"column:parent_label_id"`
	SubLabelID     int32     `db:"sub_label_id" json:"sub_label_id" gorm:"column:sub_label_id"`
}

// TableName returns the PostgreSQL table represented by LabelSubLabel.
func (LabelSubLabel) TableName() string { return "label_sub_label" }

// LabelURL represents a row in label_url.
type LabelURL struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	Hash           int32     `db:"hash" json:"hash" gorm:"column:hash"`
	URL            string    `db:"url" json:"url" gorm:"column:url"`
	LabelID        int32     `db:"label_id" json:"label_id" gorm:"column:label_id"`
}

// TableName returns the PostgreSQL table represented by LabelURL.
func (LabelURL) TableName() string { return "label_url" }

// Master represents a row in master.
type Master struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	DataQuality    *string   `db:"data_quality" json:"data_quality" gorm:"column:data_quality"`
	Title          *string   `db:"title" json:"title" gorm:"column:title"`
	Year           *int16    `db:"year" json:"year" gorm:"column:year"`
	MainReleaseID  *int32    `db:"main_release_id" json:"main_release_id" gorm:"column:main_release_id"`
}

// TableName returns the PostgreSQL table represented by Master.
func (Master) TableName() string { return "master" }

// MasterArtist represents a row in master_artist.
type MasterArtist struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	ArtistID       int32     `db:"artist_id" json:"artist_id" gorm:"column:artist_id"`
	MasterID       int32     `db:"master_id" json:"master_id" gorm:"column:master_id"`
}

// TableName returns the PostgreSQL table represented by MasterArtist.
func (MasterArtist) TableName() string { return "master_artist" }

// MasterGenre represents a row in master_genre.
type MasterGenre struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	Genre          string    `db:"genre" json:"genre" gorm:"column:genre"`
	MasterID       int32     `db:"master_id" json:"master_id" gorm:"column:master_id"`
}

// TableName returns the PostgreSQL table represented by MasterGenre.
func (MasterGenre) TableName() string { return "master_genre" }

// MasterStyle represents a row in master_style.
type MasterStyle struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	MasterID       int32     `db:"master_id" json:"master_id" gorm:"column:master_id"`
	Style          string    `db:"style" json:"style" gorm:"column:style"`
}

// TableName returns the PostgreSQL table represented by MasterStyle.
func (MasterStyle) TableName() string { return "master_style" }

// MasterVideo represents a row in master_video.
type MasterVideo struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	Hash           int32     `db:"hash" json:"hash" gorm:"column:hash"`
	Description    *string   `db:"description" json:"description" gorm:"column:description"`
	Title          *string   `db:"title" json:"title" gorm:"column:title"`
	URL            *string   `db:"url" json:"url" gorm:"column:url"`
	MasterID       int32     `db:"master_id" json:"master_id" gorm:"column:master_id"`
}

// TableName returns the PostgreSQL table represented by MasterVideo.
func (MasterVideo) TableName() string { return "master_video" }

// ReleaseItem represents a row in release_item.
type ReleaseItem struct {
	ID                int32      `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt         time.Time  `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt    time.Time  `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	Country           *string    `db:"country" json:"country" gorm:"column:country"`
	DataQuality       *string    `db:"data_quality" json:"data_quality" gorm:"column:data_quality"`
	HasValidDay       *bool      `db:"has_valid_day" json:"has_valid_day" gorm:"column:has_valid_day"`
	HasValidMonth     *bool      `db:"has_valid_month" json:"has_valid_month" gorm:"column:has_valid_month"`
	HasValidYear      *bool      `db:"has_valid_year" json:"has_valid_year" gorm:"column:has_valid_year"`
	IsMaster          *bool      `db:"is_master" json:"is_master" gorm:"column:is_master"`
	MasterID          *int32     `db:"master_id" json:"master_id" gorm:"column:master_id"`
	ListedReleaseDate *string    `db:"listed_release_date" json:"listed_release_date" gorm:"column:listed_release_date"`
	Notes             *string    `db:"notes" json:"notes" gorm:"column:notes"`
	ReleaseDate       *time.Time `db:"release_date" json:"release_date" gorm:"column:release_date"`
	Status            *string    `db:"status" json:"status" gorm:"column:status"`
	Title             *string    `db:"title" json:"title" gorm:"column:title"`
}

// TableName returns the PostgreSQL table represented by ReleaseItem.
func (ReleaseItem) TableName() string { return "release_item" }

// ReleaseItemArtist represents a row in release_item_artist.
type ReleaseItemArtist struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	ArtistID       int32     `db:"artist_id" json:"artist_id" gorm:"column:artist_id"`
	ReleaseItemID  int32     `db:"release_item_id" json:"release_item_id" gorm:"column:release_item_id"`
}

// TableName returns the PostgreSQL table represented by ReleaseItemArtist.
func (ReleaseItemArtist) TableName() string { return "release_item_artist" }

// ReleaseItemCreditedArtist represents a row in release_item_credited_artist.
type ReleaseItemCreditedArtist struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	Hash           int32     `db:"hash" json:"hash" gorm:"column:hash"`
	Role           *string   `db:"role" json:"role" gorm:"column:role"`
	ArtistID       int32     `db:"artist_id" json:"artist_id" gorm:"column:artist_id"`
	ReleaseItemID  int32     `db:"release_item_id" json:"release_item_id" gorm:"column:release_item_id"`
	IdentitySHA256 []byte    `db:"identity_sha256" json:"identity_sha256" gorm:"column:identity_sha256"`
}

// TableName returns the PostgreSQL table represented by ReleaseItemCreditedArtist.
func (ReleaseItemCreditedArtist) TableName() string { return "release_item_credited_artist" }

// ReleaseItemFormat represents a row in release_item_format.
type ReleaseItemFormat struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	Hash           int32     `db:"hash" json:"hash" gorm:"column:hash"`
	Description    *string   `db:"description" json:"description" gorm:"column:description"`
	Name           *string   `db:"name" json:"name" gorm:"column:name"`
	Quantity       *int32    `db:"quantity" json:"quantity" gorm:"column:quantity"`
	Text           *string   `db:"text" json:"text" gorm:"column:text"`
	ReleaseItemID  int32     `db:"release_item_id" json:"release_item_id" gorm:"column:release_item_id"`
	IdentitySHA256 []byte    `db:"identity_sha256" json:"identity_sha256" gorm:"column:identity_sha256"`
	QuantityText   *string   `db:"quantity_text" json:"quantity_text" gorm:"column:quantity_text"`
}

// TableName returns the PostgreSQL table represented by ReleaseItemFormat.
func (ReleaseItemFormat) TableName() string { return "release_item_format" }

// ReleaseItemGenre represents a row in release_item_genre.
type ReleaseItemGenre struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	Genre          string    `db:"genre" json:"genre" gorm:"column:genre"`
	ReleaseItemID  int32     `db:"release_item_id" json:"release_item_id" gorm:"column:release_item_id"`
}

// TableName returns the PostgreSQL table represented by ReleaseItemGenre.
func (ReleaseItemGenre) TableName() string { return "release_item_genre" }

// ReleaseItemIdentifier represents a row in release_item_identifier.
type ReleaseItemIdentifier struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	Hash           int32     `db:"hash" json:"hash" gorm:"column:hash"`
	Description    *string   `db:"description" json:"description" gorm:"column:description"`
	Type           *string   `db:"type" json:"type" gorm:"column:type"`
	Value          *string   `db:"value" json:"value" gorm:"column:value"`
	ReleaseItemID  int32     `db:"release_item_id" json:"release_item_id" gorm:"column:release_item_id"`
	IdentitySHA256 []byte    `db:"identity_sha256" json:"identity_sha256" gorm:"column:identity_sha256"`
}

// TableName returns the PostgreSQL table represented by ReleaseItemIdentifier.
func (ReleaseItemIdentifier) TableName() string { return "release_item_identifier" }

// ReleaseItemImage represents a row in release_item_image.
type ReleaseItemImage struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	Hash           int32     `db:"hash" json:"hash" gorm:"column:hash"`
	FileName       *string   `db:"file_name" json:"file_name" gorm:"column:file_name"`
	ReleaseItemID  int32     `db:"release_item_id" json:"release_item_id" gorm:"column:release_item_id"`
	IdentitySHA256 []byte    `db:"identity_sha256" json:"identity_sha256" gorm:"column:identity_sha256"`
}

// TableName returns the PostgreSQL table represented by ReleaseItemImage.
func (ReleaseItemImage) TableName() string { return "release_item_image" }

// ReleaseItemStyle represents a row in release_item_style.
type ReleaseItemStyle struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	ReleaseItemID  int32     `db:"release_item_id" json:"release_item_id" gorm:"column:release_item_id"`
	Style          string    `db:"style" json:"style" gorm:"column:style"`
}

// TableName returns the PostgreSQL table represented by ReleaseItemStyle.
func (ReleaseItemStyle) TableName() string { return "release_item_style" }

// ReleaseItemTrack represents a row in release_item_track.
type ReleaseItemTrack struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	Hash           int32     `db:"hash" json:"hash" gorm:"column:hash"`
	Duration       *string   `db:"duration" json:"duration" gorm:"column:duration"`
	Position       *string   `db:"position" json:"position" gorm:"column:position"`
	Title          *string   `db:"title" json:"title" gorm:"column:title"`
	ReleaseItemID  int32     `db:"release_item_id" json:"release_item_id" gorm:"column:release_item_id"`
	IdentitySHA256 []byte    `db:"identity_sha256" json:"identity_sha256" gorm:"column:identity_sha256"`
}

// TableName returns the PostgreSQL table represented by ReleaseItemTrack.
func (ReleaseItemTrack) TableName() string { return "release_item_track" }

// ReleaseItemVideo represents a row in release_item_video.
type ReleaseItemVideo struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	Hash           int32     `db:"hash" json:"hash" gorm:"column:hash"`
	Description    *string   `db:"description" json:"description" gorm:"column:description"`
	Title          *string   `db:"title" json:"title" gorm:"column:title"`
	URL            *string   `db:"url" json:"url" gorm:"column:url"`
	ReleaseItemID  int32     `db:"release_item_id" json:"release_item_id" gorm:"column:release_item_id"`
	IdentitySHA256 []byte    `db:"identity_sha256" json:"identity_sha256" gorm:"column:identity_sha256"`
}

// TableName returns the PostgreSQL table represented by ReleaseItemVideo.
func (ReleaseItemVideo) TableName() string { return "release_item_video" }

// ReleaseItemWork represents a row in release_item_work.
type ReleaseItemWork struct {
	ID             int32     `db:"id" json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	CreatedAt      time.Time `db:"created_at" json:"created_at" gorm:"column:created_at"`
	LastModifiedAt time.Time `db:"last_modified_at" json:"last_modified_at" gorm:"column:last_modified_at"`
	Hash           int32     `db:"hash" json:"hash" gorm:"column:hash"`
	Work           *string   `db:"work" json:"work" gorm:"column:work"`
	LabelID        int32     `db:"label_id" json:"label_id" gorm:"column:label_id"`
	ReleaseItemID  int32     `db:"release_item_id" json:"release_item_id" gorm:"column:release_item_id"`
	IdentitySHA256 []byte    `db:"identity_sha256" json:"identity_sha256" gorm:"column:identity_sha256"`
}

// TableName returns the PostgreSQL table represented by ReleaseItemWork.
func (ReleaseItemWork) TableName() string { return "release_item_work" }

// Style represents a row in style.
type Style struct {
	Name string `db:"name" json:"name" gorm:"column:name;primaryKey"`
}

// TableName returns the PostgreSQL table represented by Style.
func (Style) TableName() string { return "style" }
