version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '02:45'
      timezone: Asia/Seoul
    groups:
      go-dependencies:
        patterns:
          - '*'
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '03:00'
      timezone: Asia/Seoul
    groups:
      gradle-dependencies:
        patterns:
          - '*'
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '03:15'
      timezone: Asia/Seoul
    groups:
      github-actions:
        patterns:
          - '*'
    commit-message:
      prefix: ci
      include: scope
