plugins {
    id 'java-library'
    id 'maven-publish'
    id 'org.springframework.boot' version '2.5.1'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'org.liquibase.gradle' version '2.0.3'
    id 'nu.studer.jooq' version '5.2.2'
}

bootJar.enabled(false)
jar.enabled(true)
jar.archiveClassifier.set('')

group 'io.dsub.discogs'
version '0.0.4'

sourceCompatibility = JavaVersion.VERSION_16
targetCompatibility = JavaVersion.VERSION_16

java {
    withSourcesJar()
    withJavadocJar()
}

repositories {
    mavenCentral()
    maven { url "https://plugins.gradle.org/m2/" }
}

dependencies {
    jooqGenerator (
            'org.slf4j:slf4j-simple:1.7.9',
            'org.postgresql:postgresql',
            'org.testcontainers:postgresql:1.21.4',
    )
    api(
            'org.jooq:jooq',
    )
    liquibaseRuntime (
            'org.liquibase:liquibase-core:3.8.1',
            'org.liquibase:liquibase-groovy-dsl:2.1.1',
            'javax.xml.bind:jaxb-api:2.3.1',
            'org.postgresql:postgresql',
            'org.yaml:snakeyaml:1.15'
    )
}

publishing {
    repositories {
        maven {
            name = "centralStaging"
            url = layout.buildDirectory.dir("central-staging")
        }
    }
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'discogs-jooq'
            from components.java
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
            pom {
                name = 'discogs-jooq'
                description = 'Generated jOOQ schema classes for Discogs data services.'
                url = 'https://github.com/state303/discogs-jooq'
                inceptionYear = '2021'

                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                        distribution = 'repo'
                    }
                }

                developers {
                    developer {
                        id = 'state303'
                        name = 'Seunghyun Bae'
                        email = 'state303@linux.com'
                        organization = 'DSUB'
                        organizationUrl = 'https://www.dsub.io'
                        roles = ['developer', 'maintainer']
                    }
                }

                scm {
                    connection = 'scm:git:https://github.com/state303/discogs-jooq.git'
                    developerConnection = 'scm:git:ssh://git@github.com/state303/discogs-jooq.git'
                    url = 'https://github.com/state303/discogs-jooq'
                    tag = 'v0.0.4'
                }

                issueManagement {
                    system = 'GitHub'
                    url = 'https://github.com/state303/discogs-jooq/issues'
                }
            }
        }
    }
}

// jooq
jooq {
    configurations {
        main {
            generationTool {
                logging = org.jooq.meta.jaxb.Logging.WARN
                jdbc {
                    driver = "org.testcontainers.jdbc.ContainerDatabaseDriver"
                    url = "jdbc:tc:postgresql:///databasename?TC_INITSCRIPT=file:${projectDir}/src/main/resources/postgresql-init.sql"
                }
                generator {
                    name = 'org.jooq.codegen.JavaGenerator'
                    database {
                        inputSchema = 'public'
                    }
                    generate {
                        deprecated = false
                        records = true
                        immutablePojos = false
                        fluentSetters = true
                        javaTimeTypes = true
                    }
                    target {
                        packageName = 'io.dsub.discogs.jooq'
                        directory = "build/generated/main"  // default (can be omitted)
                    }
                    strategy.name = 'org.jooq.codegen.DefaultGeneratorStrategy'
                }
            }
        }
    }
}

liquibase {
    activities {
        configure {
            main {
                changeLogFile 'src/main/resources/db/changelog/db.changelog-master.yaml'
                url System.getenv('POSTGRES_URL')
                username System.getenv('POSTGRES_USER')
                password System.getenv('POSTGRES_PASSWORD')
                changeSetAuthor System.getenv('AUTHOR')
            }
        }
    }
}

tasks.named('generateJooq').configure {
    // make jOOQ task participate in incremental builds (which is also a prerequisite for participating in build caching)
    allInputsDeclared = true

    // make jOOQ task participate in build caching
    outputs.cacheIf { true }
}

tasks.withType(Javadoc).configureEach {
    options.addStringOption('Xdoclint:none', '-quiet')
}

tasks.withType(Jar).configureEach {
    metaInf {
        from(rootProject.file('LICENSE'))
        from(rootProject.file('NOTICE'))
    }
}
