package main

import (
	"bufio"
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
	"unicode"
)

type column struct {
	name          string
	dataType      string
	nullable      bool
	primaryKey    bool
	autoIncrement bool
}

type table struct {
	name    string
	columns []column
}

func main() {
	inputPath := flag.String("input", "", "PostgreSQL catalog TSV input")
	outputPath := flag.String("output", "", "generated Go output")
	flag.Parse()

	if *inputPath == "" || *outputPath == "" {
		exit(errors.New("both -input and -output are required"))
	}

	tables, err := readCatalog(*inputPath)
	if err != nil {
		exit(err)
	}
	source, err := generate(tables)
	if err != nil {
		exit(err)
	}
	if err := os.WriteFile(*outputPath, source, 0o644); err != nil {
		exit(fmt.Errorf("write generated model: %w", err))
	}
}

func exit(err error) {
	_, _ = fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}

func readCatalog(path string) ([]table, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open catalog: %w", err)
	}
	defer func() { _ = file.Close() }()

	tableIndexes := make(map[string]int)
	var tables []table
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		fields := strings.Split(scanner.Text(), "\t")
		if len(fields) != 8 {
			return nil, fmt.Errorf("invalid catalog row with %d fields: %q", len(fields), scanner.Text())
		}
		tableName := fields[0]
		index, exists := tableIndexes[tableName]
		if !exists {
			index = len(tables)
			tableIndexes[tableName] = index
			tables = append(tables, table{name: tableName})
		}
		tables[index].columns = append(tables[index].columns, column{
			name:          fields[1],
			dataType:      fields[2],
			nullable:      fields[4] == "YES",
			primaryKey:    fields[6] == "true",
			autoIncrement: fields[7] == "true",
		})
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("read catalog: %w", err)
	}
	if len(tables) == 0 {
		return nil, errors.New("catalog contains no public tables")
	}
	sort.Slice(tables, func(left, right int) bool {
		return tables[left].name < tables[right].name
	})
	return tables, nil
}

func generate(tables []table) ([]byte, error) {
	var source bytes.Buffer
	source.WriteString("// Code generated by internal/modelgen. DO NOT EDIT.\n\n")
	source.WriteString("package model\n\n")
	source.WriteString("import \"time\"\n\n")
	source.WriteString("// TableNames contains every table represented by this model release.\n")
	source.WriteString("var TableNames = []string{\n")
	for _, item := range tables {
		_, _ = fmt.Fprintf(&source, "\t%q,\n", item.name)
	}
	source.WriteString("}\n\n")

	for _, item := range tables {
		structName := exportedName(item.name)
		_, _ = fmt.Fprintf(&source, "// %s represents a row in %s.\n", structName, item.name)
		_, _ = fmt.Fprintf(&source, "type %s struct {\n", structName)
		for _, field := range item.columns {
			goType, err := columnType(field)
			if err != nil {
				return nil, fmt.Errorf("%s.%s: %w", item.name, field.name, err)
			}
			tag := "column:" + field.name
			if field.primaryKey {
				tag += ";primaryKey"
			}
			if field.autoIncrement {
				tag += ";autoIncrement"
			}
			_, _ = fmt.Fprintf(
				&source,
				"\t%s %s `db:%q json:%q gorm:%q`\n",
				exportedName(field.name),
				goType,
				field.name,
				field.name,
				tag,
			)
		}
		source.WriteString("}\n\n")
		_, _ = fmt.Fprintf(
			&source,
			"// TableName returns the PostgreSQL table represented by %s.\n",
			structName,
		)
		_, _ = fmt.Fprintf(
			&source,
			"func (%s) TableName() string { return %q }\n\n",
			structName,
			item.name,
		)
	}

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w\n%s", err, source.String())
	}
	return formatted, nil
}

func columnType(field column) (string, error) {
	var goType string
	switch field.dataType {
	case "bigint":
		goType = "int64"
	case "boolean":
		goType = "bool"
	case "bytea":
		if field.name != "identity_sha256" {
			return "", fmt.Errorf("unsupported bytea column %q", field.name)
		}
		goType = "SHA256Digest"
	case "character", "character varying", "text":
		goType = "string"
	case "date", "timestamp with time zone", "timestamp without time zone":
		goType = "time.Time"
	case "integer":
		goType = "int32"
	case "smallint":
		goType = "int16"
	default:
		return "", fmt.Errorf("unsupported PostgreSQL type %q", field.dataType)
	}
	if field.nullable {
		return "*" + goType, nil
	}
	return goType, nil
}

func exportedName(value string) string {
	acronyms := map[string]string{
		"etag":   "ETag",
		"id":     "ID",
		"sha256": "SHA256",
		"uri":    "URI",
		"url":    "URL",
	}
	parts := strings.Split(value, "_")
	for index, part := range parts {
		if acronym, exists := acronyms[part]; exists {
			parts[index] = acronym
			continue
		}
		runes := []rune(part)
		if len(runes) == 0 {
			continue
		}
		runes[0] = unicode.ToUpper(runes[0])
		parts[index] = string(runes)
	}
	return strings.Join(parts, "")
}
